name: First attempt at actions

on: [push]

jobs:
  run-shell-cmd:
    runs-on: ubuntu-latest
    steps:
      - name: first step echo something
        run: echo "bash installed by default"
      - name: a python command
        run: |
          import platform
          print(platform.processor())
        shell: python

  second-shell-cmd:
    runs-on: ubuntu-latest
    needs: 
      - last-cmd
    steps:
      - name: step pytyhon something
        run: python -V

  last-cmd:
    runs-on: ubuntu-latest
    steps:
      - name: last action
        run: |
          import platform
          print(platform.node())
        shell: python